// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employees.proto

package com.kishorek.protos;

public final class EmployeeDBProtos {
  private EmployeeDBProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Employee_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Employee_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Employee_EmploymentInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_Employee_EmploymentInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_EmployeeDB_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_EmployeeDB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017employees.proto\022\010tutorial\"\341\001\n\010Employee" +
      "\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(\005\022\r\n\005email\030\003 \001(" +
      "\t\022/\n\004info\030\004 \001(\0132!.tutorial.Employee.Empl" +
      "oymentInfo\032S\n\016EmploymentInfo\022\014\n\004dept\030\001 \001" +
      "(\t\0223\n\004type\030\002 \001(\0162\032.tutorial.Employee.Emp" +
      "Type:\tPERMANENT\"&\n\007EmpType\022\r\n\tPERMANENT\020" +
      "\000\022\014\n\010CONTRACT\020\001\"2\n\nEmployeeDB\022$\n\010employe" +
      "e\030\001 \003(\0132\022.tutorial.EmployeeB)\n\023com.kisho" +
      "rek.protosB\020EmployeeDBProtosP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_Employee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Employee_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "Info", });
    internal_static_tutorial_Employee_EmploymentInfo_descriptor =
      internal_static_tutorial_Employee_descriptor.getNestedTypes().get(0);
    internal_static_tutorial_Employee_EmploymentInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_Employee_EmploymentInfo_descriptor,
        new java.lang.String[] { "Dept", "Type", });
    internal_static_tutorial_EmployeeDB_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_EmployeeDB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_EmployeeDB_descriptor,
        new java.lang.String[] { "Employee", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
