// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employees.proto

package com.kishorek.protos;

public interface EmployeeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.Employee)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 id = 2;</code>
   */
  boolean hasId();
  /**
   * <code>optional int32 id = 2;</code>
   */
  int getId();

  /**
   * <code>optional string email = 3;</code>
   */
  boolean hasEmail();
  /**
   * <code>optional string email = 3;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>optional .tutorial.Employee.EmploymentInfo info = 4;</code>
   */
  boolean hasInfo();
  /**
   * <code>optional .tutorial.Employee.EmploymentInfo info = 4;</code>
   */
  com.kishorek.protos.Employee.EmploymentInfo getInfo();
  /**
   * <code>optional .tutorial.Employee.EmploymentInfo info = 4;</code>
   */
  com.kishorek.protos.Employee.EmploymentInfoOrBuilder getInfoOrBuilder();
}
