# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: employees.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='employees.proto',
  package='tutorial',
  syntax='proto2',
  serialized_options=_b('\n\023com.kishorek.protosB\020EmployeeDBProtosP\001'),
  serialized_pb=_b('\n\x0f\x65mployees.proto\x12\x08tutorial\"\xe1\x01\n\x08\x45mployee\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12/\n\x04info\x18\x04 \x01(\x0b\x32!.tutorial.Employee.EmploymentInfo\x1aS\n\x0e\x45mploymentInfo\x12\x0c\n\x04\x64\x65pt\x18\x01 \x01(\t\x12\x33\n\x04type\x18\x02 \x01(\x0e\x32\x1a.tutorial.Employee.EmpType:\tPERMANENT\"&\n\x07\x45mpType\x12\r\n\tPERMANENT\x10\x00\x12\x0c\n\x08\x43ONTRACT\x10\x01\"2\n\nEmployeeDB\x12$\n\x08\x65mployee\x18\x01 \x03(\x0b\x32\x12.tutorial.EmployeeB)\n\x13\x63om.kishorek.protosB\x10\x45mployeeDBProtosP\x01')
)



_EMPLOYEE_EMPTYPE = _descriptor.EnumDescriptor(
  name='EmpType',
  full_name='tutorial.Employee.EmpType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PERMANENT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTRACT', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=217,
  serialized_end=255,
)
_sym_db.RegisterEnumDescriptor(_EMPLOYEE_EMPTYPE)


_EMPLOYEE_EMPLOYMENTINFO = _descriptor.Descriptor(
  name='EmploymentInfo',
  full_name='tutorial.Employee.EmploymentInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dept', full_name='tutorial.Employee.EmploymentInfo.dept', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='tutorial.Employee.EmploymentInfo.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=215,
)

_EMPLOYEE = _descriptor.Descriptor(
  name='Employee',
  full_name='tutorial.Employee',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tutorial.Employee.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='tutorial.Employee.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='tutorial.Employee.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='tutorial.Employee.info', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_EMPLOYEE_EMPLOYMENTINFO, ],
  enum_types=[
    _EMPLOYEE_EMPTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=255,
)


_EMPLOYEEDB = _descriptor.Descriptor(
  name='EmployeeDB',
  full_name='tutorial.EmployeeDB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='employee', full_name='tutorial.EmployeeDB.employee', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=307,
)

_EMPLOYEE_EMPLOYMENTINFO.fields_by_name['type'].enum_type = _EMPLOYEE_EMPTYPE
_EMPLOYEE_EMPLOYMENTINFO.containing_type = _EMPLOYEE
_EMPLOYEE.fields_by_name['info'].message_type = _EMPLOYEE_EMPLOYMENTINFO
_EMPLOYEE_EMPTYPE.containing_type = _EMPLOYEE
_EMPLOYEEDB.fields_by_name['employee'].message_type = _EMPLOYEE
DESCRIPTOR.message_types_by_name['Employee'] = _EMPLOYEE
DESCRIPTOR.message_types_by_name['EmployeeDB'] = _EMPLOYEEDB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Employee = _reflection.GeneratedProtocolMessageType('Employee', (_message.Message,), dict(

  EmploymentInfo = _reflection.GeneratedProtocolMessageType('EmploymentInfo', (_message.Message,), dict(
    DESCRIPTOR = _EMPLOYEE_EMPLOYMENTINFO,
    __module__ = 'employees_pb2'
    # @@protoc_insertion_point(class_scope:tutorial.Employee.EmploymentInfo)
    ))
  ,
  DESCRIPTOR = _EMPLOYEE,
  __module__ = 'employees_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Employee)
  ))
_sym_db.RegisterMessage(Employee)
_sym_db.RegisterMessage(Employee.EmploymentInfo)

EmployeeDB = _reflection.GeneratedProtocolMessageType('EmployeeDB', (_message.Message,), dict(
  DESCRIPTOR = _EMPLOYEEDB,
  __module__ = 'employees_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.EmployeeDB)
  ))
_sym_db.RegisterMessage(EmployeeDB)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
